### PR TITLE
Update tests/README to include sphinx-build instructions

### PR DESCRIPTION
**Pull request by dwalton76**

### CODE REVIEW

**Comment by dwalton76** [comment]
One snag is when I use the `-W` flag it barfs due to
```
robot@ev3dev:~/ev3dev-lang-python$ sphinx-build -nW -b html ./docs/ ./docs/_build/html
Running Sphinx v1.4.9
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: 16 added, 0 changed, 0 removed
reading sources... [100%] wheels

Warning, treated as error:
README.rst:None: WARNING: nonlocal image URI found: https://travis-ci.org/ev3dev/ev3dev-lang-python.svg?branch=ev3dev-stretch

robot@ev3dev:~/ev3dev-lang-python$
```

Without the `-W` flag 
```
robot@ev3dev:~/ev3dev-lang-python$ sphinx-build -n -b html ./docs/ ./docs/_build/html
Running Sphinx v1.4.9
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: 16 added, 0 changed, 0 removed
reading sources... [100%] wheels
README.rst:None: WARNING: nonlocal image URI found: https://travis-ci.org/ev3dev/ev3dev-lang-python.svg?branch=ev3dev-stretch
README.rst:None: WARNING: nonlocal image URI found: https://readthedocs.org/projects/python-ev3dev/badge/?version=ev3dev-stretch
README.rst:None: WARNING: nonlocal image URI found: https://badges.gitter.im/ev3dev/chat.svg
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] wheels
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.beep:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.tone:29: WARNING: py:meth reference target not found: play_song
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.tone:None: WARNING: py:obj reference target not found: list[tuple(float,float,float)]
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_tone:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_tone:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_note:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_note:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_file:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_file:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.speak:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.speak:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.speak:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_song:None: WARNING: py:obj reference target not found: iterable[tuple(string,
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_song:None: WARNING: py:obj reference target not found: int
generating indices... genindex
writing additional pages... search
copying images... [100%] _static/fonts.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 17 warnings.
robot@ev3dev:~/ev3dev-lang-python$
```

I am not familiar with sphinx so I am not sure how critical the `-W` flag is and if it would be fine to omit it from the README instructions.  The CI tests are still going to use `-W` so it would probably be fine but it would be better to figure out how to get the to run correctly and update the README accordingly.

**Comment by WasabiFan** [comment]
I believe `-W` is "treat warnings as errors". So it's not crucial but most of the failures that you'll get in CI will be warnings so you'll miss most issues.

How about we add it to the ignore list?

```
suppress_warnings = ['image.nonlocal_uri']
```

**Comment by dwalton76** [comment]
``sphinx-build -n -D suppress_warnings='image.nonlocal_uri'  -b html ./docs/ ./docs/_build/html`` seems like the best tradeoff at the moment (note the lack of ``-W``).  This still shows the user these warnings:
```
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.beep:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.tone:29: WARNING: py:meth reference target not found: play_song
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.tone:None: WARNING: py:obj reference target not found: list[tuple(float,float,float)]
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_tone:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_tone:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_note:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_note:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_file:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_file:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.speak:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.speak:None: WARNING: py:obj reference target not found: string
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.speak:None: WARNING: py:obj reference target not found: int
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_song:None: WARNING: py:obj reference target not found: iterable[tuple(string,
/home/robot/ev3dev-lang-python/ev3dev2/sound.py:docstring of ev3dev2.sound.Sound.play_song:None: WARNING: py:obj reference target not found: int
```

But those look like things we should fix and not suppress

**Comment by WasabiFan** [comment]
Why not just add that warning ignore to our existing global list?

**Comment by dwalton76** [comment]
I couldn't find where we have a defined list (``git grep suppress_warnings`` says we do not have one) and have yet to find the correct syntax for the command line to tell sphinx to ignore multiple types of warnings.

**Comment by WasabiFan** [comment]
It looks like I was thinking of this:

https://github.com/ev3dev/ev3dev-lang-python/blob/195259f1c54b1fecf08257e762f748406acd2538/docs/conf.py#L316-L326

So we just have to add `suppress_warnings = ['image.nonlocal_uri']` to that conf file.

**Review by WasabiFan — APPROVED** [review]
Assuming the instructions work for you, this looks good.

**Pull request merged**
