### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by dwalton76**
This corrects all warning/errors found by flake8

### CODE REVIEW

**Comment by dwalton76** [comment]
For issue #714

**Comment by WasabiFan** [comment]
This seems generally OK, but I think a lot of this functionality should be tested if we're making these changes, because some of it could have introduced bugs.

**Comment by dwalton76** [comment]
@wasabifan I’ll do some testing tonight and then merge. I looked through the patch again and all of the changes look pretty trivial so I think after some basic testing we should be good.

**Comment by dwalton76** [comment]
I did some testing...all seems fine.

**Pull request merged**
