### PR TITLE
StopWatch class

### PR DESCRIPTION
**Pull request by dwalton76**
For #629

### CODE REVIEW

**Comment by dwalton76** [comment]
Tested via
```
    try:
        from time import sleep
    except ImportError:
        from utime import sleep

    sw = StopWatch()

    # start the timer, sleep, print value
    sw.start()
    print("sleep(2)")
    sleep(2)
    sw.stop()
    print("%s -> %s" % (sw.value_ms, sw.value_hms))

    # sleep without the timer running
    print("sleep(3)")
    sleep(3)

    # start the timer, sleep, print value
    sw.start()
    print("sleep(4)")
    sleep(4)
    sw.stop()
    print("%s -> %s" % (sw.value_ms, sw.value_hms))

    sw.start()
    for x in range(20):
        print("%d: %s -> %s" % (x, sw.value_ms, sw.value_hms))
        sleep(0.1)

    sw.reset()
```

**Comment by WasabiFan** [comment]
Is this custom code or is it copied from somewhere? If copied, are there licensing requirements?

**Comment by dwalton76** [comment]
It is custom.

**Review by WasabiFan — APPROVED** [review]
This looks good to me!

**Comment by WasabiFan** [comment]
We probably need to add this to the docs index so it shows up in the docs

**Pull request merged**
