### PR TITLE
Add gitter.im badge

### PR DESCRIPTION
**Pull request by ddemidov**

### CODE REVIEW

**Comment by WasabiFan** [comment]
@dlech are you :+1: with us directing Python questions into the ev3dev channel? Just want to confirm.

**Comment by ddemidov** [comment]
Or we could add a subchannel.

**Comment by WasabiFan** [comment]
I personally don't have much of an opinion either way, given that the ev3dev channel generally isn't busy enough that this would conflict.

**Comment by dlech** [comment]
The more, the merrier, I say. :smile:

**Review by WasabiFan — APPROVED** [review]

**Pull request merged**
