### PR TITLE
debian: update control file for ev3dev-lang-python 2.x

### PR DESCRIPTION
**Pull request by dlech**
This changes the name of the debian package so that the 2.x version can be installed at the same time as the 1.x version

### CODE REVIEW

**Comment by dlech** [comment]
Maybe update the Maintainer: field too? :smile:

**Review by ddemidov — APPROVED** [review]

**Comment by WasabiFan** [comment]
How is it that the package name is `python-ev3dev` yet IIRC it's installed as `python3-ev3dev`?

**Comment by dlech** [comment]
the first package listed is the source package. The second package is the binary package, which is `python3-ev3dev2`. The binary package is the one that gets installed.

**Comment by WasabiFan** [comment]
Got it. What's the use case for source packages for Python libraries?

**Review by WasabiFan — APPROVED** [review]

**Comment by WasabiFan** [comment]
Thanks for the PR!

Re: maintainer field, can it be a list of multiple people?

**Comment by ddemidov** [comment]
> can it be a list of multiple people?

or a team name?

**Comment by dlech** [comment]
> What's the use case for source packages for Python libraries?

All debian packages have a source package, because, you know, open source :wink:.

You can, for example, download this with `apt source python-ev3dev`.

> Re: maintainer field, can it be a list of multiple people?

Nope.

> or a team name?

Sure, as long as there is a valid email address to go with it.

**Pull request merged**
