### PR TITLE
LED animation fix duration None

### PR DESCRIPTION
**Pull request by dwalton76**
mat.volfik@gmail.com is the original author of this patch

### CODE REVIEW

**Comment by dwalton76** [comment]
We haven't heard from mvolfik for a few months so I grabbed his/her patch (from #665) , addressed the code review comments and posted a new PR. Will give them credit or the patch in the commit message.

**Comment by WasabiFan** [comment]
As with the other PR; please retain the authorship info on the commits.

**Comment by dwalton76** [comment]
got the commit log edited to list mvolfik...merging this one

**Comment by WasabiFan** [comment]
When this was merged with GitHub's squash button it overwrote the author 🙃  Changelog will have to do.

**Pull request merged**
