### PR TITLE
Remove Stretch-only changes accidentally introduced to Jessie branch

### PR DESCRIPTION
**Pull request by WasabiFan**
#466

### CODE REVIEW

**Comment by ddemidov** [comment]
There is some problem with `ev3dev-lang-fake-sys` submodule. The `jessie` branch points to @rhempel's version of it, and the `stretch` branch points to mine. I think both should point to https://github.com/ev3dev/ev3dev-lang-fake-sys. The error in travis seems to be caused by this.

**Comment by ddemidov** [comment]
Correction, the jessie branch correctly points to https://github.com/ev3dev/ev3dev-lang-fake-sys; this PR tries to update it?

And while stretch branch does point to mine version of ev3dev-lang-fake-sys, it is correctly redirected to ev3dev one (but we still need to update the address I think).

**Comment by WasabiFan** [comment]
It looks like the current Jessie branch points to rhempel/ev3dev-lang-fake-sys. I don't understand why exactly it failed, but I'll see if I can switch it to point to the ev3dev instance and go from there.

**Comment by WasabiFan** [comment]
This needs to be rebased after #477 is merged.

**Review by ddemidov — APPROVED** [review]

**Pull request merged**
