### PR TITLE
Bring documentation up-to-date with the develop branch

### LINKED ISSUE #441: Documentation should be updated for the new project layout
While trying to fix #440, I noticed that the generated documentation is empty: http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/latest/motors.html. Most likely, the documentation still links to the classes with old file structure.

### PR DESCRIPTION
**Pull request by ddemidov**
Uses the new project structure in sphinx docs, fixes a couple of docstring issues.

Fixes #441

### CODE REVIEW

**Comment by ddemidov** [comment]
The result should be visible here: http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/doc-issues-441/

**Comment by WasabiFan** [comment]
This is included (in part) by https://github.com/ev3dev/ev3dev-lang-python/pull/411; I'll need to rebase that branch when this is merged. Looks good to me though.

**Comment by ddemidov** [comment]
For some reason readthedocs does not rebuild the documentation automatically on each commit. Builds need to be triggered manually. @dlech, can you make sure this repo has the readthedocs service enabled?
screenshot from 2018-01-12 22-16-19

**Comment by dlech** [comment]
I checked and it was enabled already. I hit the test button, which should trigger a build, I think.

**Pull request merged**
