### PR TITLE
format code via yapf

### PR DESCRIPTION
**Pull request by dwalton76**
Formatted via
```
dwalton@laptop:ev3dev-lang-python$ yapf --style .yapf.cfg --in-place --recursive . 
dwalton@laptop:ev3dev-lang-python$ 
dwalton@laptop:ev3dev-lang-python$ cat .yapf.cfg 
[style]
based_on_style = pep8
COLUMN_LIMIT = 120
dwalton@laptop:ev3dev-lang-python$ 
```

### CODE REVIEW

**Comment by dwalton76** [comment]
This patch is ~4300 lines.

**Comment by WasabiFan** [comment]
It doesn't look like this includes the yapf config or the make targets like you added in the other PR. Was that intentional? I think we should have the configuration included.

**Comment by dwalton76** [comment]
oops, config and make target have been added now

**Comment by dwalton76** [comment]
@WasabiFan this one look ok to merge? We can do a pre-commit hook via another commit/issue.

**Comment by WasabiFan** [comment]
Yeah, this looks good to me. Hopefully no one was working on a big PR :laughing:

**Pull request merged**
