### PR TITLE
"address" argument on LEDs #422

### PR DESCRIPTION
**Pull request by dwalton76**

### CODE REVIEW

**Review by WasabiFan — APPROVED** [review]
should  the `__str__` implementation be overridden to print the device name in this case?

**Comment by dwalton76** [comment]
It will print the class name if there is no “address”...not sure what the device name would be for the LEDs?

**Comment by WasabiFan** [comment]
I believe the the led structure is `/sys/class/leds/<device_name>/...` such that the name describes which LED it is. That would be the useful information to provide.

**Comment by dwalton76** [comment]
ok so `self.__class__.__name__` will print something like `<ev3dev.ev3.Leds object at 0xb6710dd0>`...I was expecting just `Leds` here I am not sure where this is coming from.

**Comment by dwalton76** [comment]
ah, is it because `class Leds` does not inherit from `class Device`

**Comment by dwalton76** [comment]
quick summary:
- the Led and Leds classes are off on their own right now in terms of `__str__`.  Will fix these up.
- for any Motor object there will be an address so `Device.__str__()` will print something like `LargeMotor(outA)`
- Sensor objects typically don't have an `address` specified so `Device.__str__()` will print just the class name.  I kinda like this because it is nice and simple and not too long...if we print all of `self._path` for that object that is going to be really long.

**Comment by dwalton76** [comment]
This
```
leds = Leds()
log.info("%s: is the Leds object" % leds)
log.info("%s: is a single Led object" % leds.leds['red_left'])
```

results in
```
2018-01-31 03:45:22,179  INFO: Leds: is the Leds object
2018-01-31 03:45:22,217  INFO: red_left: is a single Led object
```

For a single Led object the desc is almost always going to be set so we get the handy `red_left` output

**Comment by WasabiFan** [comment]
Looks good to me! It might be nice to have the class name in there too but I don't think it makes much of a difference; we should avoid over-complicating things.

**Pull request merged**
